### ISSUE TITLE
Icons: Add Chiron up and down

### ISSUE THREAD

**Issue by cseas** [hazel-ui/hazel-ui#5]
Setup the foundation for adding Icons in the project. Add Chiron up and down as examples and use them in the table for sorting.

**Comment by jmahesh123** [comment]
can i work on this issue?

**Comment by cseas** [comment]
Sure, you can try adding an "Icons" component under `foundation`.
Then we should be able to use `<Icons.ChironUp />` and `<Icons.ChironDown />` to replace the [emoji arrows used here](https://github.com/hazel-ui/hazel-ui/blob/f54d2803150fea3469b2a8818a99e663a86cf4d7/src/components/Table/Table.tsx#L66).

**Comment by cseas** [comment]
Some progress on this has been made in #17 and #29 
Tasks left:
- [x] Add Arrow icons as React components
- [ ] Add story for Icon component
- [x] Replace static strings in Table component with Arrow icons

**Comment by jmahesh123** [comment]
Thanks for feedback.
I will raise another PR for above points.

**Comment by jmahesh123** [comment]
@cseas : What you mean by "Add Chiron icons as React components" . Can you help me in understanding?
Do we need to download SVG/PNG of sort icons and replace with strings in the IconComponent?

**Comment by cseas** [comment]
`Icon.ChironUp` is a string right now and there really is no way to customize that as a component.

When ChironUp is a component, we can optionally add props to it if needed in the future. For example:

`<Icon.ChironUp color="red" />`

I think if you just replace the strings with `svg` elements, the Chiron icons will automatically become a JSX type element to which props can be added.

Basically, the `Icon` component is useless if the icon inside it can't be customized in some way. The above way is just a suggestion but the end goal is that a user should be able to make `<Icon.ChironUp />` (for example) look whatever way they like in terms of size, opacity, color, etc.

**Comment by cseas** [comment]
#23 and #26 depend on this

**Comment by cseas** [comment]
Only adding the story and documentation is left for this. Created new Issue #30 for remaining work.
