### ISSUE TITLE
Table: Add prop to hide headers

### ISSUE THREAD

**Issue by cseas** [hazel-ui/hazel-ui#7]
Add optional prop `hideHeaders` to remove the table's column headers.

**Comment by jmahesh123** [comment]
Is issue fixed, If not can i work on this?

**Comment by cseas** [comment]
Yes, this has been fixed. You can see the `hideHeaders` control in the Table works as expected now:
https://hazel-ui.github.io/hazel-ui/?path=/story/atoms-table--basic
