### ISSUE TITLE
Badge: Create component

### ISSUE THREAD

**Issue by cseas** [hazel-ui/hazel-ui#9]
Add a Badge component that can be used for tags in a blog post.
Colours should be customizable.

**Comment by jmahesh123** [comment]
Can i work on this feature? Please add more details

Thanks

**Comment by cseas** [comment]
Greetings, @jmahesh123!

The Badge component is supposed to look something like the topic tags at the top of [this page](https://blog.glugmvit.com/aws-cli/). You can also find similar topic tags at the bottom of every [Medium](http://medium.com/) article.

The library's goal is to remain as flexible as possible so the colors of the Badge component should optionally be customizable. This can be done by using the `color` utility from [styled-system](https://styled-system.com/api#color).

You can refer to the code from the [Button component](https://github.com/hazel-ui/hazel-ui/blob/main/src/components/Button/Button.tsx) since the Badge component is very similar to that one. It would be great if you can add a subtle hover effect to the Badge component as well just like the Button component has, but a bit smaller.

We're looking for something very similar to [this Badge component](https://next--storybookjs.netlify.app/official-storybook/?path=/story/basics-badge--all-badges) but more flexible in nature so the user can make the badge look like whatever they want. I think adding the border utility from styled-system might help as well so the user can control the border radius of the component.

Some examples:
![Selection_006](https://user-images.githubusercontent.com/29686866/97084421-80350180-1634-11eb-98a6-d4e735d9c162.png)
![Selection_007](https://user-images.githubusercontent.com/29686866/97084422-86c37900-1634-11eb-86a0-321c9a51cada.png)
![Selection_008](https://user-images.githubusercontent.com/29686866/97084424-8a570000-1634-11eb-81c2-986581a3639b.png)
![Selection_009](https://user-images.githubusercontent.com/29686866/97084734-ba070780-1636-11eb-8e3a-b2a9b9e967ba.png)

**Comment by cseas** [comment]
Some progress made in #20
Tasks left:
- [x] Add rectangular badges as primary example (Refer images in previous comment)
- [x] Add storybook "Tip" badge as example [Reference](https://hazel-ui.github.io/hazel-ui/?path=/story/introduction--page)
- [x] Reproduce GitHub badges as examples
- [x] Remove custom example with border. Badges usually don't have a border.

**Comment by cseas** [comment]
Closed with #25
